### ISSUE TITLE
Forward otlp/gRPC and otlp/http from microshift to the systemd collector

### ISSUE THREAD

**Issue by frzifus** [os-observability/opentelemetry-collector-rhde-config#2]
In order to be able to transmit otlp data from microshift, we want to create a service that forwards data to the collector. (otlp/gRPC and otlp/http).

Not sure if there is a k8s feature like nodeport but the other way around or if we have to deploy another collector from the MicroShift registry.

Socat would be another option:
```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: otel-forwarder
  namespace: observability
spec:
  selector:
    matchLabels:
      app: socat
  template:
    metadata:
      labels:
        app: socat
    spec:
      hostNetwork: true
      containers:
      - name: socat
        image: alpine/socat
        command: ["socat", "TCP-LISTEN:4317,reuseaddr,fork", "TCP:localhost:4317"]
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: observability
spec:
  type: NodePort
  selector:
    app: otel-forwarder
  ports:
    - protocol: TCP
      port: 4317
      targetPort: 4317
    - protocol: TCP
      port: 4318
      targetPort: 4318
```
